name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        redis: [rc, latest, 7.0]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Set up Go 1.22
      uses: actions/setup-go@v5
      with:
        go-version-file: "go.mod"
      id: go

    - name: Get dependencies
      run: go mod download
        
    - name: Unit Test
      run: go test -tags unit -v .

    - name: Integration Test
      env:
        REDIS_VERSION: ${{ matrix.redis }}
      run: go test -tags integration -v .

    - name: Coverage
      run: go test -tags=unit,integration -v -covermode=count .

    - name: Build
      run: go build -v .
